"""Pydantic models for the bagent audit analyzer."""

from models.analysis import (
    DescriptionAnalysisResult,
    NamingAnalysisResult,
    QualityReport,
    StructureAnalysisResult,
)
from models.competitor import (
    ActionPlanItem,
    CompetitiveAdvantage,
    CompetitorPromotion,
    CompetitorReportData,
    CompetitorRequest,
    LocalRanking,
    MarketNiche,
    MarketSummary,
    PerServicePrice,
    PriceCategoryComparison,
    RadarMetric,
    Recommendation,
    ServiceGapEntry,
    SwotAnalysis,
)
from models.optimization import (
    CategoryMapping,
    ChangeRecord,
    OptimizationRequest,
    OptimizationResult,
    OptimizationSummary,
    OptimizedService,
    QualityVerification,
)
from models.report import (
    AuditIssue,
    AuditStats,
    CompetitorContext,
    CompetitorInfo,
    EnhancedAuditReport,
    IndustryComparison,
    MissingSeoKeyword,
    QuickWin,
    ScoreBreakdown,
    SalonLocation,
    ServiceTransformation,
)
from models.scraped_data import (
    ScrapedCategory,
    ScrapedData,
    ScrapedService,
    ServiceVariant,
)

__all__ = [
    "ActionPlanItem",
    "AuditIssue",
    "AuditStats",
    "CategoryMapping",
    "ChangeRecord",
    "CompetitiveAdvantage",
    "CompetitorContext",
    "CompetitorInfo",
    "CompetitorPromotion",
    "CompetitorReportData",
    "CompetitorRequest",
    "DescriptionAnalysisResult",
    "EnhancedAuditReport",
    "IndustryComparison",
    "LocalRanking",
    "MarketNiche",
    "MarketSummary",
    "MissingSeoKeyword",
    "NamingAnalysisResult",
    "OptimizationRequest",
    "OptimizationResult",
    "OptimizationSummary",
    "OptimizedService",
    "PerServicePrice",
    "PriceCategoryComparison",
    "QualityReport",
    "QualityVerification",
    "QuickWin",
    "RadarMetric",
    "Recommendation",
    "SalonLocation",
    "ScoreBreakdown",
    "ScrapedCategory",
    "ScrapedData",
    "ScrapedService",
    "ServiceGapEntry",
    "ServiceTransformation",
    "ServiceVariant",
    "StructureAnalysisResult",
    "SwotAnalysis",
]
